networks:
  ext_network:
    internal: false

services:
  mariadb:
    env_file:
      - ./.env
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
    name: mariadb_data